### ISSUE TITLE
ReferenceError: utsname is not defined since 8.8.0

### ISSUE THREAD

**Issue by jkatins** [NativeScript/ios#259]
In my NativeScript app I'm using this piece of code to get the device code:

```typescript
declare const utsname: Object;
declare const uname: (pointer: interop.AdoptedPointer) => void;

const utsnamePtr = interop.alloc(interop.sizeof(utsname));
uname(utsnamePtr);
const deviceCode = NSString.stringWithUTF8String(utsnamePtr.add(256 * 4)).toString();
```

This works fine with `@nativescript/ios` @ `8.7.2` but stops working with `8.8.0`. The latest `8.8.1` also doesn't work.

At runtime it throws `ReferenceError: utsname is not defined`. When removing the reference to `utsname`, it throws `ReferenceError: uname is not defined`. 

Any ideas?

**Comment by brooklax** [comment]
same issue on our side which is affecting some libs we use. some more info here: https://github.com/NativeScript/plugins/issues/596

**Comment by edusperoni** [comment]
This was just fixed in: https://github.com/NativeScript/ios/commit/55c5c5198f04ff2b5cbe1be6f5add92acb3ed23f

Apparently, ViisonOS support disabled CLANG_MODULES which is needed for us to generate uname (and others from the Darwin module). To fix this until we release a new version, you should be able to use `CLANG_ENABLE_MODULES = YES;` in your build.xcconfig

**Comment by jkatins** [comment]
@edusperoni The problem still exists in 8.8.2.

The commit you linked, as far as I can see, changes the template file for you _new_ projects. What about existing projects?

Adding `CLANG_ENABLE_MODULES = YES;` to my `build.xcconfig` results in this error when launching the app: 

```
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error:
Error calling module function
ReferenceError: CFRunLoopGetCurrent is not defined
File: (<unknown>:8:34)
StackTrace:
      construct(:8:35)
      at __webpack_require__.e(file: src/webpack:/myproject/webpack/runtime/ensure chunk:5:0)
      at __webpack_require__.X(file: src/webpack:/myproject/webpack/runtime/startup entrypoint:5:0)
      at (file:///app/bundle.js:6076:47)
      at (file:///app/bundle.js:6081:3)
      at require(:1:232)
```
